# Generated by Django 4.2.16 on 2024-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainFruit',
        ),
    ]
